### PR TITLE
Format transaction history dates (fixes #306)

### LINKED ISSUE #306: Format transaction history dates correctly
https://github.com/mozilla/payments-ui/pull/303/ has a placeholder for transaction dates. Instead of this:

    2015-08-07T14:53:23.966

it should appear like:

    Aug 7, 2015

### PR DESCRIPTION
**Pull request by kumar303**
Fixes https://github.com/mozilla/payments-ui/issues/306

### CODE REVIEW

**Comment by muffinresearch** [comment]
How are the locale files in the deps used or is this not locale specific?

**Comment by kumar303** [comment]
ugh, it looks like this pulled in all locales and added 1MB to the management bundle. Let me see what I can do.

**Comment by kumar303** [comment]
@muffinresearch aha, I found a lighter replace for moment: [fecha](https://github.com/taylorhakes/fecha). Another r?

**Comment by muffinresearch** [comment]
r+

**Pull request merged**
