### PR TITLE
Rough hack to submit payment

### PR DESCRIPTION
**Pull request by kumar303**
Depends on https://github.com/mozilla/payments-service/pull/23

### CODE REVIEW

**Comment by kumar303** [comment]
@muffinresearch this is yours to do with as you please :) If you want to merge and play with it then go for it. If you want to re-do the code in the router style then feel free to close.

You'll need to go into your Braintree sandbox and set up some products. The easiest way to do that is to run this in solitude:

    ./manage.py braintree_config

It will tell you when a product is missing or if its price is incorrect. What I did was run it, add the product in braintree, then run it again.

**Comment by muffinresearch** [comment]
You might want to rebase against master. Travis was borked due to a peerDependency issue  with webpack (caused by the peerDependency having a new release higher than the max version) which I've just fixed.

**Comment by muffinresearch** [comment]
Will take a look at this tomorrow. See https://github.com/mozilla/payments-ui/pull/54 for the router conversion

**Comment by muffinresearch** [comment]
Closing in favour of #58

**Pull request closed without merging**
