### PR TITLE
Updated react-redux to version 3.0.1

### PR DESCRIPTION
**Pull request by tofumatt**
:rocket:

One of your dependencies has just updated, so this PR bumps the corresponding version number in your `package.json`.

You can now check that the dependency update doesn't break your code, and then release the new version of your software safe in the knowledge that it will stay in this working state, regardless of _when_ your users do `$ npm install`.

Have a good day!

---

This pull request was created by [greenkeeper.io](http://greenkeeper.io/).
It keeps your software, up to date, all the time.

<sub>
Tired of seeing this sponsor message? Upgrade to the supporter plan!
You'll also get your pull requests faster :zap:
</sub>

### CODE REVIEW

**Comment by tofumatt** [comment]
Moving to a major new version seems like something we should manually test out, but all the tests pass so that's promising.

**Comment by muffinresearch** [comment]
Yeah for redux upgrades it makes sense to do redux + react-redux together. The other one failed so that'll need looking into anyway.

**Comment by muffinresearch** [comment]
v4.0 is coming and should be changed along with the update to react 0.14 See https://github.com/rackt/react-redux/releases/tag/v4.0.0

**Comment by muffinresearch** [comment]
Going to close this as it's been superceded by a newer version.

**Pull request closed without merging**
